### PR TITLE
Update third screen

### PR DESCRIPTION
**Pull request by diegoserranoa**
Add support for third screen settings values from the Admin panel.

Changes
- Update 3rd screens
- Add tests

## Test

There are lots of combinations of how this can work, so please test each one of them to make sure nothing is being missed. The third screen setup of the Settings will be your friend here, since that's where all the changes happen, so it's useful to check that whatever is being shown in mobile, should match what is shown in the Preview there.

Screen Shot 2019-10-10 at 3 11 50 AM

Like I mentioned there are many combinations, this list should help with testing:

- [x] Empty values on database, empty values on code: should show the default message.
- [x] Empty values on database, value set on code: should show the value set by code.
- [x] Value set on database, empty values on code: should show the value set on the db.
- [x] Value set on database, value set on code: should show the value set by code.
- [x] Works for all scores (negative, neutral, positive)
- [x] If using `Unique by score`, it shows default value when value is not set (e.g. promoter thank you message is set, but empty for passives and detractors
- [x] Works on tablets
- [x] Works on different account types (NPS, CES, CSAT)
- [x] Test Add email to link
- [x] Test Score email to link
- [x] Test Comment email to link

### CODE REVIEW

**Comment by prabhatjha** [comment]
@ambarwootric Pls help test this.

**Comment by ambarwootric** [comment]
Hey @diegoserranoa thank you for working on this, to be more clear with PR it would be great if you could also provide code examples of methods that can be used to customize values for third screen? attributes from DB? and just to be clear this PR changes assumes to be working from both side -- meaning if I change the values in screen it effects the mobile surveys and if I change/setup code/methods it corresponds the change in preview as mentioned?

**Comment by ambarwootric** [comment]
Thank you Diego, that's gonna help. I will let you know again.

**Comment by diegoserranoa** [comment]
Hi @ambarwootric any update on this? Have you been able to test? Let me know if you need more help!

**Comment by diegoserranoa** [comment]
@ambarwootric thanks for reviewing! I've fixed both issues you mentioned.

As for testing the second commit: it should be the same as the first. You want to see that these checkboxes are working as expected
Screen Shot 2019-11-13 at 4 10 47 PM

**Pull request merged**
